name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          # Cache dependencies for the Next.js app only
          cache: 'npm'

      # Install dependencies excluding the functions directory
      - name: Install dependencies
        run: |
          npm ci
        env:
          # Use this to prevent postinstall scripts from running which might touch the functions directory
          CI: true

      # Build Next.js application
      - name: Build with Next.js
        run: npx --no-install next build

      # Export Next.js application to static HTML
      - name: Static HTML export with Next.js
        run: npx --no-install next export

      # Upload the 'out' directory as an artifact for deployment job to pick up
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out
          name: nextjs-site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: nextjs-site

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
